export const FIRST_COUNT_INCREMENT = "FIRST_COUNT_INCREMENT";
export const FIRST_COUNT_DECREMENT = "FIRST_COUNT_DECREMENT";
export const FIRST_COUNT_CLEAR = "FIRST_COUNT_CLEAR";

export const SECOND_COUNT_INCREMENT = "SECOND_COUNT_INCREMENT";
export const SECOND_COUNT_DECREMENT = "SECOND_COUNT_DECREMENT";
export const SECOND_COUNT_CLEAR = "SECOND_COUNT_CLEAR";
